### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by Whizanth** [nsde/stray#1]
Hello,

I run a small librehost called [LibreNode](https://www.librenode.org), the same name as your library.

Back when I chose the name, I did a quick search and found that nobody was using it, so shortly after, I proceeded by registering the domain librenode.org (and since then also libreno.de). Then a couple months later I tried searching for my site on search engines to see if it has already been indexed, and found out that you have a project with the same name.

I think it would be beneficial for both of us if we weren't both using the same name. I would like to ask if there is any chance you'd be willing to change the name of your project for something else.

I tried contacting you via both e-mail and Matrix, but have gotten no reply, hence I'm opening an issue here. If you want to talk with us in more detail, or would like help with suggestions for a new name, you can join our [Matrix room](https://matrix.to/#/#general:librenode.org).

Wishing you all the best.
Thanks.

**Comment by nsde** [comment]
Hello there!

> Back when I chose the name, I did a quick search and found that nobody was using it, so shortly after, I proceeded by registering the domain librenode.org (and since then also libreno.de).

I actually thought about registering `libreno.de` too, as I'm German and thus the domain will cost close to nothing. 

> I think it would be beneficial for both of us if we weren't both using the same name.
You might be right.

> I would like to ask if there is any chance you'd be willing to change the name of your project for something else.
Sure, no problem.

> I tried contacting you via both e-mail and Matrix, but have gotten no reply, hence I'm opening an issue here.
I'm really sorry for not responding. I've just gotten a new PC and haven't set up any E-Mail app yet, and I'm only checking my E-Mails when I need to verify my account or so. I don't use Matrix actively anymore, too.

Thanks for taking the time to contact me and it is not an issue for me that you've opened an *ìssue* in this repo, as that's the reason we have them for.

***

Anyways, I'm willing to change my name.

But that would also mean a lot of time and effort, because I'm actively running multiple *Minecraft* game-servers which I'd have to shut down and/or notify the users that I need to re-write the code base.
Re-branding my logos and icons will also be quite time-consuming. Additionally, I'm a student and working on this project all by myself. Thus, this might take a few days.

Nonetheless, I'm very happy to see that you're not running any cloud hosting service, but one with privacy respecting & open source services. Thus, I'd love to contribute by, say, creating a CSS for your website. For free, of course.

Kind regards,
Felix

**Comment by nsde** [comment]
Alright, everything should be renamed now. 
Feel free to re-open this if anything else should be discussed!

**Comment by Whizanth** [comment]
I just got to the PC, thank you for dealing with this so quickly.

I've already started working on the CSS of the website, I have a specific idea of how I would like it to look, and I wouldn't want you to bother anyways, as I'm already really thankful that you took the time to change the logos and stuff.

But if you really want to contribute somehow, you said you run Minecraft game servers, is there any chance you also know something about Minetest? It's a similar game in concept, but it's free & open-source, and we're looking to set up a server instance of it in the future to support free & open-source gaming, but it seems to require a steep learning curve and I myself don't know that much about it. If not, we will have plenty of other projects in the future that you can contribute to if you feel like it.

Anyways, since you said you're still a stundent and working on this project alone, if you can give me a Bitcoin or Monero wallet address, I am willing to send you a small amount as a form of thanking you.

Have a nice day.
